<?php
/**
 * ModifiersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PHP Point Of Sale API
 *
 * PHP Point Of Sale API  You can find out more about PHP POS at [https://phppointofsale.com](https://phppointofsale.com)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@phppointofsale.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ModifiersApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ModifiersApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addModifier
     *
     * Add a new modifier to the store.
     *
     */
    public function testAddModifier()
    {
    }

    /**
     * Test case for batchModifier
     *
     * Bulk create, update, and delete modifiers.
     *
     */
    public function testBatchModifier()
    {
    }

    /**
     * Test case for deleteModifier
     *
     * Deletes a modifier.
     *
     */
    public function testDeleteModifier()
    {
    }

    /**
     * Test case for getModifierByID
     *
     * Find modifier by modifier number or ID.
     *
     */
    public function testGetModifierByID()
    {
    }

    /**
     * Test case for searchModifiers
     *
     * List modifiers.
     *
     */
    public function testSearchModifiers()
    {
    }

    /**
     * Test case for updateModifier
     *
     * Update a modifier.
     *
     */
    public function testUpdateModifier()
    {
    }
}
