<?php
session_start();
require_once('tcpdf/tcpdf.php');
 include('queries.php');
// create new PDF document
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor($_SESSION["user"]);
$pdf->SetTitle('Kwanza Tukule Report');
$pdf->SetSubject('Report');
$pdf->SetKeywords('PDF, Report, export');

// set default header data
$pdf->SetHeaderData("", PDF_HEADER_LOGO_WIDTH, "Report","Generated By: ".$_SESSION["user"]);

// set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// set some language-dependent strings (optional)
if (@file_exists(dirname(__FILE__).'/lang/eng.php')) {
    require_once(dirname(__FILE__).'/lang/eng.php');
    $pdf->setLanguageArray($l);
}

// ---------------------------------------------------------

// set font
$pdf->SetFont('helvetica', '', 10);

// add a page
$pdf->AddPage();
$date = date( 'l, F d, Y ', time());
$result1 = mysqli_fetch_array($monthSalesValue);
$sales = $result1['sum'];
$result2 = mysqli_fetch_array($monthIncomeValue);
$income = $result2['sum'];
$result3 = mysqli_fetch_array($monthExpenseValue);
$expenses = $result3['sum'];
$result4 = mysqli_fetch_array($salariesTotal);
$salaries = $result4['salaries'];
$gross_profit_loss = '';
$gross = $income - $sales;
if ($gross > 0) {
  $gross_profit_loss = 'profit';
}
elseif ($gross < 0) {
  $gross_profit_loss = 'loss';
}
$net_profit_loss = '';
$net = $gross - $expenses - $salaries;
if ($net > 0) {
  $net_profit_loss = 'profit';
}
elseif ($net < 0) {
  $net_profit_loss = 'loss';
}
$result5 = mysqli_fetch_array($lastmonthSalesValue);
$last_sales = $result5['sum'];
$result6 = mysqli_fetch_array($lastmonthIncomeValue);
$last_income = $result6['sum'];
$result7 = mysqli_fetch_array($lastmonthExpenseValue);
$last_expenses = $result7['sum'];
$last_gross = $last_income - $last_sales;
$gross_up_down = '';
if ($last_gross < $gross) {
 $gross_up_down = 'an upward';
}
elseif ($last_gross > $gross) {
  $gross_up_down = 'a downward';
}
$gross_pc = ($gross/($last_gross + $gross)) * 100;
$last_net = $last_gross - $last_expenses - $salaries;
$net_up_down = '';
if ($last_net < $net) {
  $net_up_down = 'an upward';
}
elseif ($last_net > $net) {
  $net_up_down = 'a downward';
}
$net_pc = ($gross/($last_net + $net)) * 100;
$last_gross_up_down = '';
if ($last_gross > 0) {
  $last_gross_up_down = 'profit';
}
elseif ($last_gross < 0) {
  $last_gross_up_down = 'loss';
}
$last_net_up_down = '';
if ($last_net > 0) {
  $last_net_up_down = 'profit';
}
elseif ($last_net < 0) {
  $last_net_up_down = 'loss';
}
 $fastmovingproducts = array();
  foreach($fastmovingMonth as $row){
  $name = $row['name'];
  $total = $row['sum'];
  $resultArrayfast = array($name, $total);
  array_push($fastmovingproducts, $resultArrayfast);
  }
  $slowmovingproducts = array();
  foreach($slowmovingMonth as $row){
  $name = $row['name'];
  $total = $row['sum'];
  $resultArrayslow = array($name, $total);
  array_push($slowmovingproducts, $resultArrayslow);
  }
  $payerList = array();
  foreach($biggestPayers as $row){
  $name = $row['name'];
  $total = $row['sum'];
  $resultArray = array($name, $total);
  array_push($payerList, $resultArray);
  }
  $result8 = mysqli_fetch_array($customersTotalMonth);
  $customersTotal = $result8['count'];
  $result9 = mysqli_fetch_array($customersTotalLastMonth);
  $customersTotalLast = $result9['count'];
$customers_difference = '';
if ($customersTotal > $customersTotalLast) {
  $customers_difference = 'an improvement';
}
elseif ($customersTotal < $customersTotalLast) {
  $customers_difference = 'a drop';
}
  $customersrowcount = mysqli_num_rows($customersList);
 $result9 = mysqli_fetch_array($customersTotalLastMonth);
  $customersTotalLast = $result9['count'];
  $result10 = mysqli_fetch_array($newCustomersMonthCount);
  $newCustomersMonthCount = $result10['count'];
$newCustomerStatement = '';
if ($newCustomersMonthCount > 0) {
  $newCustomerStatement = 'This past one month we have had <b>'.$newCustomersMonthCount.' new customer(s)</b>. The new customers with their respective locations and amount of money they have paid to the company are as follows:
  <ol>';
  foreach($newCustomersMonth as $rows){
  $newName = $rows['Name'];
  $newLocation = $rows['Location'];
  $amount = $rows['sum'];
  $newCustomerStatement .= '<b><li>'.$newName.' - '.$newLocation.' - Ksh. '.$amount.'</li></b>';
  }
  $newCustomerStatement .= '</ol>';
}
elseif ($newCustomersMonthCount == 0) {
  $newCustomerStatement = 'This past one month we had <b>no new customers</b>. Sales should be done by the team for a positive improvement.';
}
$result11 = mysqli_fetch_array($monthLiability);
  $monthLiability = $result11['sum'];
$result12 = mysqli_fetch_array($totalLiability);
  $totalLiability = $result12['sum'];  
// writeHTML($html, $ln=true, $fill=false, $reseth=false, $cell=false, $align='')
// writeHTMLCell($w, $h, $x, $y, $html='', $border=0, $ln=0, $fill=0, $reseth=true, $align='', $autopadding=true)

// create some HTML content
$html = '<h1 style="text-align:center"><strong><img src="assets/img/Kwanza Tukule.png" height="80" width="200"></strong></h1>
<b>Date: '.$date.'</b><br>
<h3>Purpose</h3>
    <p>
      We exist to make a positive difference in the livelihoods of our people socially and economically by providing them food supply services prepared under the utmost standards of hygiene and sanitation, using sustainable sources of renewable energy, allowing them to maximize their potential.
    </p>
    <h3>Vision</h3>
    <p>
      To Make Nutritious food affordable for the many.
    </p>
    <h3>Mission Statement</h3>
    <p>
      We reliably offer better food supply chain in Africa that feeds the community with affordable, healthy, nutritious foods, prepared under the utmost standards of hygiene that allow our clients to overcome food insecurity, post-harvest losses and energy consumption/ that allow our clients to enjoy a delicious meal while saving time and conserving energy.
    </p>
    <h2>Performance Analysis</h2>
<p>Below is the report that examines the company performance for the last one month.</p>
<p>This month we managed to <b>sale products worth Ksh. '.$sales.'</b>. This income for sale of different products whose demands depended on the customers preferences. The <b>5 most demanded products</b> this month with the corresponding sales quantities(units) were as follows:</p>
<ol>
    <b><li>'.$fastmovingproducts[0][0].' - '.$fastmovingproducts[0][1].'</li>
    <li>'.$fastmovingproducts[1][0].' - '.$fastmovingproducts[1][1].'</li>
    <li>'.$fastmovingproducts[2][0].' - '.$fastmovingproducts[2][1].'</li>
    <li>'.$fastmovingproducts[3][0].' - '.$fastmovingproducts[3][1].'</li>
    <li>'.$fastmovingproducts[4][0].' - '.$fastmovingproducts[4][1].'</li></b>
</ol>
<p>On the other hand the <b>5 least  demanded</b> products of the month with their corresponding sales quantities(units) were as follows:</p>
<ol>
    <b><li>'.$slowmovingproducts[0][0].' - '.$slowmovingproducts[0][1].'</li>
    <li>'.$slowmovingproducts[1][0].' - '.$slowmovingproducts[1][1].'</li>
    <li>'.$slowmovingproducts[2][0].' - '.$slowmovingproducts[2][1].'</li>
    <li>'.$slowmovingproducts[3][0].' - '.$slowmovingproducts[3][1].'</li>
    <li>'.$slowmovingproducts[4][0].' - '.$slowmovingproducts[4][1].'</li></b>
</ol>
<p>All products combined generated a <b>revenue of Ksh. '.$income.'</b>.</p>
<p>With that the <b>gross '.$gross_profit_loss.' was Ksh. '.$gross.'</b>.This is '.$gross_up_down.' gross projection by '.intval($gross_pc).'%.Last month there was a '.$last_gross_up_down.' of Ksh. '.$last_gross.'.</p>
<p>Various <b>expenses</b> were incurred during the month which <b>totaled to Ksh. '.$expenses.'</b>. Below is a breakdown of the various expense details for the past one month with their respective amounts paid and due.</p>
<table border="1" cellspacing="1" cellpadding="4" align="center">
    <tr>
        <th><b>Date of Payment</b></th>
        <th><b>Expense Title</b></th>
        <th><b>Paid Party</b></th>
        <th><b>Amount Paid</b></th>
        <th><b>Amount Due</b></th>   
    </tr>';
  foreach($expensesMonth as $row){
  $name = $row['name'];
  $party = $row['Party'];
  $paid = $row['paid'];
  $due = $row['due'];
  $date = $row['date'];
  $day = date( 'l, F d', strtotime($date) ); 
   $html .= ' <tr>
        <td>'.$day.'</td>
        <td>'.$name.'</td>
        <td>'.$name.'</td>
        <td>Ksh. '.$paid.'</td>
        <td>Ksh. '.$due.'</td>
    </tr>';
  }  
$html .= '</table>
<p>Given the data above the <b>projected '.$net_profit_loss.'</b> made during this month <b>was therefore Ksh. '.$net.'</b>.This is '.$net_up_down.' net projection by '.intval($net_pc).'%.Last month there was a '.$last_net_up_down.' of Ksh. '.$last_net.'.</p>
<p>Based on the due amounts above, the <b>added liability this month resulted to Ksh. '.$monthLiability.'</b> summing up the <b>total liability of the company to Ksh. '.$totalLiability.'</b>.</p>
<p>In the given period, a <b>total of '.$customersTotal.' customers</b> out of the total possible '.$customersrowcount.' customers have ordered various products from the company. This was '.$customers_difference.' from last month where '.$customersTotalLast.' customers made orders. '.$newCustomerStatement.'</p>

<p>In general all the customers had different payment tendencies during the period. The <b>top 5 customers who made the biggest payments</b> during the period with their corresponding payments were as follows:</p>
<ol>
    <b><li>'.$payerList[0][0].' - Ksh.'.$payerList[0][1].'</li>
    <li>'.$payerList[1][0].' - Ksh.'.$payerList[1][1].'</li>
    <li>'.$payerList[2][0].' - Ksh.'.$payerList[2][1].'</li>
    <li>'.$payerList[3][0].' - Ksh.'.$payerList[3][1].'</li>
    <li>'.$payerList[4][0].' - Ksh.'.$payerList[4][1].'</li></b>
</ol>
<p>The above customers are the new key customers for the coming month given that they made the biggest orders and made timely payments.</p>
<p>During the given period, we had deliverers who made deliveries to the various customers. Each deliverer had their own sub-set of customers that they made deliveries to. The <b>deliverers this month with their corresponding value of sales done and amount of money collected</b> durig the period are as follows:</p>
<table border="1" cellspacing="1" cellpadding="4" align="center">
    <tr>
        <th><b>Deliverer</b></th>
        <th><b>Worth of Sales</b></th>
        <th><b>Amount Collected</b></th> 
    </tr>';
  foreach($delivererSalesMonth as $row){
$deliverer = $row['deliverer'];
  $collected = $row['sum'];
  $worth = $row['worth'];
   $html .= ' <tr>
        <td>'.$deliverer.'</td>
        <td>'.$worth.'</td>
        <td>'.$collected.'</td>
    </tr>';
  }  
$html .= '</table>
<p>The table above will be used as the basis to which each and every deliverer will be credited with regards to contribution in company growth.</p>
<h2>Suppliers</h2>
<h2>Vehicles</h2>
<dl>
    <dt>Coffee</dt>
    <dd>Black hot drink</dd>
    <dt>Milk</dt>
    <dd>White cold drink</dd>
</dl>
<div style="text-align:center">IMAGES<br />
<img src="assets/img/Kwanza Tukule.png" height="60" width="155">
</div>';

// output the HTML content
$pdf->writeHTML($html, true, false, true, false, '');


// output some RTL HTML content
$html = '<div style="text-align:center">The words &#8220;<span dir="rtl">&#1502;&#1494;&#1500; [mazel] &#1496;&#1493;&#1489; [tov]</span>&#8221; mean &#8220;Congratulations!&#8221;</div>';
$pdf->writeHTML($html, true, false, true, false, '');

// test some inline CSS
$html = '<p>This is just an example of html code to demonstrate some supported CSS inline styles.
<span style="font-weight: bold;">bold text</span>
<span style="text-decoration: line-through;">line-trough</span>
<span style="text-decoration: underline line-through;">underline and line-trough</span>
<span style="color: rgb(0, 128, 64);">color</span>
<span style="background-color: rgb(255, 0, 0); color: rgb(255, 255, 255);">background color</span>
<span style="font-weight: bold;">bold</span>
<span style="font-size: xx-small;">xx-small</span>
<span style="font-size: x-small;">x-small</span>
<span style="font-size: small;">small</span>
<span style="font-size: medium;">medium</span>
<span style="font-size: large;">large</span>
<span style="font-size: x-large;">x-large</span>
<span style="font-size: xx-large;">xx-large</span>
</p>';

$pdf->writeHTML($html, true, false, true, false, '');

// reset pointer to the last page
$pdf->lastPage();

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// Print a table

// add a page
$pdf->AddPage();



// output the HTML content
$pdf->writeHTML($html, true, false, true, false, '');

// Print some HTML Cells

$html = '<span color="red">red</span> <span color="green">green</span> <span color="blue">blue</span><br /><span color="red">red</span> <span color="green">green</span> <span color="blue">blue</span>';

$pdf->SetFillColor(255,255,0);

$pdf->writeHTMLCell(0, 0, '', '', $html, 'LRTB', 1, 0, true, 'L', true);
$pdf->writeHTMLCell(0, 0, '', '', $html, 'LRTB', 1, 1, true, 'C', true);
$pdf->writeHTMLCell(0, 0, '', '', $html, 'LRTB', 1, 0, true, 'R', true);

// reset pointer to the last page
$pdf->lastPage();

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// Print a table

// add a page
$pdf->AddPage();

// create some HTML content
$html = '<h1>Image alignments on HTML table</h1>
<table cellpadding="1" cellspacing="1" border="1" style="text-align:center;">
<tr><td><img src="images/logo_example.png" border="0" height="41" width="41" /></td></tr>
<tr style="text-align:left;"><td><img src="images/logo_example.png" border="0" height="41" width="41" align="top" /></td></tr>
<tr style="text-align:center;"><td><img src="images/logo_example.png" border="0" height="41" width="41" align="middle" /></td></tr>
<tr style="text-align:right;"><td><img src="images/logo_example.png" border="0" height="41" width="41" align="bottom" /></td></tr>
<tr><td style="text-align:left;"><img src="images/logo_example.png" border="0" height="41" width="41" align="top" /></td></tr>
<tr><td style="text-align:center;"><img src="images/logo_example.png" border="0" height="41" width="41" align="middle" /></td></tr>
<tr><td style="text-align:right;"><img src="images/logo_example.png" border="0" height="41" width="41" align="bottom" /></td></tr>
</table>';

// output the HTML content
$pdf->writeHTML($html, true, false, true, false, '');

// reset pointer to the last page
$pdf->lastPage();

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// Print all HTML colors

// add a page
$pdf->AddPage();

$textcolors = '<h1>HTML Text Colors</h1>';
$bgcolors = '<hr /><h1>HTML Background Colors</h1>';

foreach(TCPDF_COLORS::$webcolor as $k => $v) {
    $textcolors .= '<span color="#'.$v.'">'.$v.'</span> ';
    $bgcolors .= '<span bgcolor="#'.$v.'" color="#333333">'.$v.'</span> ';
}

// output the HTML content
$pdf->writeHTML($textcolors, true, false, true, false, '');
$pdf->writeHTML($bgcolors, true, false, true, false, '');

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

// Test word-wrap

// create some HTML content
$html = '<hr />
<h1>Various tests</h1>
<a href="#2">link to page 2</a><br />
<font face="courier"><b>thisisaverylongword</b></font> <font face="helvetica"><i>thisisanotherverylongword</i></font> <font face="times"><b>thisisaverylongword</b></font> thisisanotherverylongword <font face="times">thisisaverylongword</font> <font face="courier"><b>thisisaverylongword</b></font> <font face="helvetica"><i>thisisanotherverylongword</i></font> <font face="times"><b>thisisaverylongword</b></font> thisisanotherverylongword <font face="times">thisisaverylongword</font> <font face="courier"><b>thisisaverylongword</b></font> <font face="helvetica"><i>thisisanotherverylongword</i></font> <font face="times"><b>thisisaverylongword</b></font> thisisanotherverylongword <font face="times">thisisaverylongword</font> <font face="courier"><b>thisisaverylongword</b></font> <font face="helvetica"><i>thisisanotherverylongword</i></font> <font face="times"><b>thisisaverylongword</b></font> thisisanotherverylongword <font face="times">thisisaverylongword</font> <font face="courier"><b>thisisaverylongword</b></font> <font face="helvetica"><i>thisisanotherverylongword</i></font> <font face="times"><b>thisisaverylongword</b></font> thisisanotherverylongword <font face="times">thisisaverylongword</font>';

// output the HTML content
$pdf->writeHTML($html, true, false, true, false, '');

// Test fonts nesting
$html1 = 'Default <font face="courier">Courier <font face="helvetica">Helvetica <font face="times">Times <font face="dejavusans">dejavusans </font>Times </font>Helvetica </font>Courier </font>Default';
$html2 = '<small>small text</small> normal <small>small text</small> normal <sub>subscript</sub> normal <sup>superscript</sup> normal';
$html3 = '<font size="10" color="#ff7f50">The</font> <font size="10" color="#6495ed">quick</font> <font size="14" color="#dc143c">brown</font> <font size="18" color="#008000">fox</font> <font size="22"><a href="http://www.tcpdf.org">jumps</a></font> <font size="22" color="#a0522d">over</font> <font size="18" color="#da70d6">the</font> <font size="14" color="#9400d3">lazy</font> <font size="10" color="#4169el">dog</font>.';

$html = $html1.'<br />'.$html2.'<br />'.$html3.'<br />'.$html3.'<br />'.$html2;

// output the HTML content
$pdf->writeHTML($html, true, false, true, false, '');

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// test pre tag

// add a page
$pdf->AddPage();

$html = <<<EOF
<div style="background-color:#880000;color:white;">
Hello World!<br />
Hello
</div>
<pre style="background-color:#336699;color:white;">
int main() {
    printf("HelloWorld");
    return 0;
}
</pre>
<tt>Monospace font</tt>, normal font, <tt>monospace font</tt>, normal font.
<br />
<div style="background-color:#880000;color:white;">DIV LEVEL 1<div style="background-color:#008800;color:white;">DIV LEVEL 2</div>DIV LEVEL 1</div>
<br />
<span style="background-color:#880000;color:white;">SPAN LEVEL 1 <span style="background-color:#008800;color:white;">SPAN LEVEL 2</span> SPAN LEVEL 1</span>
EOF;

// output the HTML content
$pdf->writeHTML($html, true, false, true, false, '');

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

// test custom bullet points for list

// add a page
$pdf->AddPage();

$html = <<<EOF
<h1>Test custom bullet image for list items</h1>
<ul style="font-size:14pt;list-style-type:img|png|4|4|images/logo_example.png">
    <li>test custom bullet image</li>
    <li>test custom bullet image</li>
    <li>test custom bullet image</li>
    <li>test custom bullet image</li>
<ul>
EOF;

// output the HTML content
$pdf->writeHTML($html, true, false, true, false, '');

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

// reset pointer to the last page
$pdf->lastPage();
//Close and output PDF document
ob_end_clean();
$pdf->Output('Report.pdf', 'I');
