<?php
require_once('tcpdf/tcpdf.php');
 include('queries.php');
            $pdf = new TCPDF('P','mm','A4');
            $pdf->SetCreator(PDF_CREATOR);
            $pdf->SetTitle("Kwanza Tukule Report");
            $pdf->SetHeaderData('','', PDF_HEADER_TITLE, PDF_HEADER_STRING);
            $pdf->SetHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
            $pdf->SetFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_MAIN));
            $pdf->SetDefaultMonospacedFont('helvetica');
            $pdf->SetFooterMargin(PDF_MARGIN_FOOTER);
            $pdf->SetMargins(PDF_MARGIN_LEFT, '5',PDF_MARGIN_RIGHT);
            $pdf->setPrintHeader(false);
            $pdf->setPrintFooter(false);
            $pdf->SetAutoPageBreak(TRUE, 10);
            $pdf->SetFont('helvetica','',12);
            $pdf->AddPage();
            $content = '';
            $content .= '
            <h2 style="text-align:center"><strong><img src="assets/img/Kwanza Tukule.png" height="60" width="155"></strong></h2>
            <br>
            <h3 style="text-align:center">Report</h3>
             <h4>Stock Flow</h4>
             <div style="text-align:center"> <h5>Purchase records shown are as at the end of day yesterday.</h5></div><br>
            
			 <br> 
			 <h4>Sales Per Deliverer</h4>
             <div id="chart_div" style="width: 1000px; height: 500px;" ></div>   
			<br>
			<h4>Brand Sales Comparison</h4>
			 <div id="piechart" style="width: 500px; height: 500px;"></div>
			 <br>   
			 <p>Generated By: <?php echo $logged_in_user; ?></p>
            ';  
            $pdf->writeHTML($content);
            ob_end_clean();
            $pdf->Output("report.pdf","I");
            /*   $pdf = new TCPDF('P', PDF_UNIT, PDF_PAGE_FORMAT, true, 'UFT-8', false);
          $pdf->SetCreator(PDF_CREATOR);
            $pdf->SetTitle("Kwanza Tukule Report");
            $pdf->SetHeaderData('','', PDF_HEADER_TITLE, PDF_HEADER_STRING);
            $pdf->SetHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
            $pdf->SetFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_MAIN));
            $pdf->SetDefaultMonospacedFont('helvetica');
            $pdf->SeFooterMargin(PDF_MARGIN_FOOTER);
            $pdf->SetMargins(PDF_MARGIN_LEFT, '5',PDF_MARGIN_RIGHT);
            $pdf->setPrintHeader(false);
            $pdf->setPrintFooter(false);
            $pdf->SetAutoPageBreak(TRUE, 10);
            $pdf->SetFont('helvetica','',12);

            $content = '';
            $content .= '
            <h2 style="text-align:center"><strong><img src="assets/img/Kwanza Tukule.png" height="60" width="155"></strong></h2>
            <br>
            <h3 style="text-align:center">Report</h3>
            <h4>Stock Flow</h4>
  <div class="row offset-3"> <h6>Purchase records shown are as at the end of day yesterday.</h6></div><br>
    <?php
     $yesterday1 = date("d/m/Y",strtotime("-2 day"));
     $yesterday2 = date("d/m/Y",strtotime("-3 day"));
     $yesterday3 = date("d/m/Y",strtotime("-4 day"));
    ?>
    <table  class="table table-striped table-hover paginate" style="display:block;overflow-y:scroll;text-align: center;">
  <thead class="thead-dark">
    <tr>
      <th scope="col" width="3%">#</th>
      <th scope="col" width="14%">Brand Name</th>
      <th scope="col" width="10%"><?php echo $yesterday3; ?></th>
      <th scope="col" width="10%"><?php echo $yesterday2; ?></th>
      <th scope="col" width="10%"><?php echo $yesterday1; ?></th>
      <th scope="col"width="10%">Yesterday</th>
      <th scope="col"width="10%">Today</th>
      <th scope="col"width="10%">Opening Stock</th>
      <th scope="col"width="10%">Closing Stock</th>
      <th scope="col"width="10%">Selling Price</th>
    </tr>
  </thead>
  <tbody >
    <?php
        $count = 0;
        foreach($valuationQuery as $row){
         $count++;
         $id = $row["sid"];
         $name = $row["sname"];
        $sum1 = $row["sum1"];
        $sum2 = $row["sum2"];
        $sum3 = $row["sum3"];
        $sum4 = $row["sum4"];
        $sum5 = $row["sum5"];
        $opening = $row["Opening_stock"];
        $closing = $row["Quantity"];
        $sp = $row["Selling_Price"];
      ?>
    <tr>
      <th scope="row"><?php echo $id; ?></th>
      <td ><?php echo $name; ?></td>
      <td ><?php echo $sum1; ?></td>
      <td ><?php echo $sum2; ?></td>
      <td ><?php echo $sum3; ?></td>
      <td ><?php echo $sum4; ?></td>
      <td ><?php echo $sum5; ?></td>
      <td ><?php echo $opening; ?></td>
      <td ><?php echo $closing; ?></td>
      <td ><?php echo $sp; ?></td>
    </tr>
    <?php
    }
    ?>
  </tbody>
</table>
<br>
<h4>Sales Per Deliverer</h4>
       <div id="chart_div" style="width: 1000px; height: 500px;" ></div>   
<br>
<h4>Brand Sales Comparison</h4>
 <div id="piechart" style="width: 500px; height: 500px;"></div>
 <br>  
 <p>Generated By: <?php echo $logged_in_user; ?></p>
            ';  
  $pdf->writeHTML($content);
  $pdf->Output("report.pdf","I");    */

?>
<script type="text/javascript">
	 google.charts.load("current", {packages:["corechart"]});
      google.charts.setOnLoadCallback(drawChart);
      function drawChart() {
         var where = 'fastmoving';
       $.post("charts.php",{where:where},
        function(result){
          var data = $.parseJSON(result);
          var data0 = data[0][0];
          var data1 = data[0][1];
          var data2 = data[1][0];
          var data3 = data[1][1];
          var data4 = data[2][0];
          var data5 = data[2][1];
          var data6 = data[3][0];
          var data7 = data[3][1];
          var data8 = data[4][0];
          var data9 = data[4][1];
          var data10 = data[5][0];
          var data11 = data[5][1];
          var data12 = data[6][0];
          var data13 = data[6][1];
        var data = google.visualization.arrayToDataTable([
          [data0, data1],
         [data2, parseInt(data3)],
          [data4, parseInt(data5)],
          [data6, parseInt(data7)],
          [data8, parseInt(data9)],
          [data10, parseInt(data11)],
          [data12, parseInt(data13)],
        ]);
        var options = {
          title: 'Fast moving products',
          legend: 'none',
          pieSliceText: 'label',
          slices: {  1: {offset: 0.2},
                    4: {offset: 0.1},
                    0: {offset: 0.2},
                    2: {offset: 0.1},
          },
        };

        var chart = new google.visualization.PieChart(document.getElementById('piechart'));
        chart.draw(data, options);
        });
      }

      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawVisualization);

      function drawVisualization() {
        var where = 'salescomparison';
       $.post("charts.php",{where:where},
        function(result){
          //alert(result);
                   var data = google.visualization.arrayToDataTable([
          ['Day', 'Royson', 'Ken', 'Reuben', 'Damaris', 'George', 'Average'],
          ['2004/06/05',  165,      938,         522,             998,           450,      614.6],
          ['2005/06/06',  135,      1120,        599,             1268,          288,      682],
          ['2006/06/07',  157,      1167,        587,             807,           397,      623],
          ['2007/06/08',  139,      1110,        615,             968,           215,      609.4],
          ['Yesterday',  136,      691,         629,             1026,          366,      569.6],
          ['Today',  136,      691,         629,             1026,          366,      569.6],
        ]);

        var options = {
          title : 'Weekly Sales Made per Deliverer',
          vAxis: {title: 'Sales'},
          hAxis: {title: 'Day'},
          seriesType: 'bars',
          series: {5: {type: 'line'}}        };

        var chart = new google.visualization.ComboChart(document.getElementById('chart_div'));
        chart.draw(data, options);
        });
      }
</script>